name: Bug report
description: Help us improve Phoenix by reporting a bug
title: "[BUG]: "
labels: ["bug", "triage"]
body:
  - type: dropdown
    id: hosting
    attributes:
      label: Where do you use Phoenix
      options:
        - Phoenix Cloud (app.phoenix.arize.com)
        - Local (self-hosted)
        - Container (self-hosted)
        - Notebook (Jupyter, Colab, etc)
  - type: input
    id: version
    attributes:
      label: What version of Phoenix are you using?
      placeholder: e.g. 8.0.0
    validations:
      required: true
  - type: input
    id: operating-system
    attributes:
      label: What operating system are you seeing the problem on?
      placeholder: e.g. macOS, Windows, Linux
    validations:
      required: true
  - type: input
    id: instrumentation-runtime
    attributes:
      label: Where does your instrumentation run?
      placeholder: e.g. Python 3.13, Node v23
  - type: textarea
    id: instrumentation
    attributes:
      label: What instrumentation are you using?
      placeholder: |
        arize-phoenix-otel==0.8.0
        openinference-instrumentation-openai==0.1.21
      description: Include package names, versions
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you saw
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: What did you expect to happen?
      placeholder: Tell us what you want to see
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: How can we reproduce the bug?
      description: Please include any code samples, screenshots, videos, or steps to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Please include any additional information that can help us with your issue.